
name: TBC-1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ test-gh-actions ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Check out code

      #- name: Build docker image
      #  run: docker build --target cpp-dev --tag cpp-dev:0.0.1 .

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: "Publish docker images to GHCR"
        with:
          image: cpp-dev
          target: cpp-dev
          registry: ghcr.io
          githubOrg: ua-snap # optional
          username: ${{ github.ua-snap }}
          password: ${{ secrets.GHCR_TOKEN }}
